name: "Deploy"

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: scp to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          repository: ${{ variables.REPOSITORY }}
          source: .
          target: /home/{{ secrets.SERVER_USERNAME }}/{{ variables.REPOSITORY }}
      - name: Deploy
        env:
          TERM: dumb
        run: |
          ./env.sh
          ./deploy.sh