name: "Test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ opened ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"
      - name: Run tests
        env:
          TERM: dumb
        run: |
          ./pytest.sh